# Generated by Django 4.2 on 2025-12-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mofidied_date',
            new_name='modified_date',
        ),
    ]
