# Generated by Django 4.2 on 2026-01-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
        ('carts', '0002_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='vatiations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
