# Generated by Django 4.2 on 2026-01-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_vatiations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='vatiations',
            new_name='variations',
        ),
    ]
